"""Add ContentRegistry model and file_hashes to StudyPath

Revision ID: 7477e6809a28
Revises: c1d0e553b531
Create Date: 2026-05-23 22:04:39.252347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7477e6809a28'
down_revision = 'c1d0e553b531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('chroma_collection', sa.String(length=128), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_collection')
    )
    with op.batch_alter_table('content_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_registry_file_hash'), ['file_hash'], unique=True)

    with op.batch_alter_table('study_paths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hashes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_paths', schema=None) as batch_op:
        batch_op.drop_column('file_hashes')

    with op.batch_alter_table('content_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_registry_file_hash'))

    op.drop_table('content_registry')
    # ### end Alembic commands ###
