"""add study_paths and lesson_progress tables

Revision ID: c1d0e553b531
Revises: a1b2c3d4e5f6
Create Date: 2026-05-18 04:32:40.417459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d0e553b531'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_paths_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_path_id', sa.String(length=36), nullable=False),
    sa.Column('module_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_path_id'], ['study_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_study_path_id'), ['study_path_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_study_path_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('study_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_paths_user_id'))

    op.drop_table('study_paths')
    # ### end Alembic commands ###
